[workspace]
members = ["scripts", "packages/*", "nibiru-std", "contracts/*"]
exclude = ["packages/msig-ez"]
resolver = "2"

# Dependencies can be inherited from a workspace by specifying the dependency in
# the `[workspace.dependencies]` table. To use workspace crates, add them to the
# `[dependencies]` table with `workspace = true`.
# ```
# anyhow = { workspace = true }
# ```
[workspace.dependencies]
# serde
serde = { version = "1.0.189", default-features = false, features = ["derive"] }
serde_json = "1.0.108"

nibiru-std = { path = "nibiru-std" }
prost = "0.12.3"
prost-types = "0.12.3"
bash-rs = { path = "packages/bash-rs" }

# deps: CosmWasm
cosmwasm-std = { version = "1.5.0", features = ["stargate", "staking"] }
cosmwasm-schema = "1.5.0"
cw-storage-plus = { version = "1.2.0" }
cw-multi-test = { version = "0.20.0" }
cw-utils = { version = "1.0.3" }
# Macros for controlling ownership of CosmWasm smart contracts
cw-ownable = { version = "0.5.1"}

# deps: cw-plus
cw2 = { version = "1.1.1" }
cw3 = { version = "1.1.1" }
cw3-fixed-multisig = { version = "1.1.1", features = ["library"] }
cw4 = { version = "1.1.1" }
cw20 = { version = "1.1.1" }

# deps: core contracts
# TODO: revive bindings-perp with stargate
# bindings-perp = { path = "core/core-bindings-perp" }
shifter = { path = "contracts/core-shifter" }
controller = { path = "contracts/core-controller" }
lockup = { path = "contracts/lockup", features = ["library"] }
incentives = { path = "contracts/incentives", features = ["library"] }
broker-bank = { path = "contracts/broker-bank", features = ["library"] }

# deps: else
anyhow = "1"
thiserror = "1.0.50"
assert_cmd = "2"
lazy_static = "1.4.0"
clap = { version = "4.4.7", features = ["derive", "cargo", "env", "string"] }
schemars = "0.8.15"
home = "0.5"
toml = "0.8"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true